/**
 * One-time migration: Vercel Blob → Cloudflare R2, plus DB URL rewrite.
 *
 *   npm run migrate:blob            # dry run — lists and plans, changes nothing
 *   npm run migrate:blob -- --write # copy objects + emit drizzle/rewrite.sql
 *
 * Env (app/.env or your shell):
 *   BLOB_READ_WRITE_TOKEN   old store (list + download)
 *   R2_ACCOUNT_ID           Cloudflare account id
 *   R2_ACCESS_KEY_ID        R2 S3 API token (Object Read+Write on the bucket)
 *   R2_SECRET_ACCESS_KEY
 *
 * The DB rewrite is EMITTED as drizzle/rewrite.sql (REPLACE() over the blob
 * host → /media/), applied with:
 *   npx wrangler d1 execute ggeran-db --local  --file=drizzle/rewrite.sql
 *   npx wrangler d1 execute ggeran-db --remote --file=drizzle/rewrite.sql
 *
 * The Vercel Blob store is NOT touched (cold backup); delete it manually only
 * after the new site has been verified end to end.
 */
import "dotenv/config";
import { list } from "@vercel/blob";
import { AwsClient } from "aws4fetch";
import { mkdirSync, writeFileSync } from "node:fs";

const WRITE = process.argv.includes("--write");

const required = ["BLOB_READ_WRITE_TOKEN", "R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY"];
for (const k of required) {
  if (!process.env[k]) {
    console.error(`✗ ${k} is not set (add it to app/.env or the shell).`);
    process.exit(1);
  }
}

const r2 = new AwsClient({
  accessKeyId: process.env.R2_ACCESS_KEY_ID!,
  secretAccessKey: process.env.R2_SECRET_ACCESS_KEY!,
  region: "auto",
  service: "s3",
});
const R2_BASE = `https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com/ggeran-media`;

const contentTypeFor = (pathname: string): string => {
  const ext = pathname.split(".").pop()?.toLowerCase();
  return ext === "png" ? "image/png" : ext === "webp" ? "image/webp" : "image/jpeg";
};

// ── 1. List the old store ─────────────────────────────────────────────────
console.log("→ listing Vercel Blob store…");
const blobs: { url: string; pathname: string; size: number }[] = [];
let cursor: string | undefined;
do {
  const res = await list({ cursor, limit: 1000 });
  for (const b of res.blobs) blobs.push({ url: b.url, pathname: b.pathname, size: b.size });
  cursor = res.hasMore ? res.cursor : undefined;
} while (cursor);
console.log(`  ${blobs.length} blobs, ${(blobs.reduce((a, b) => a + b.size, 0) / 1024 / 1024).toFixed(1)} MB total.`);

if (blobs.length === 0) {
  console.log("Nothing to migrate.");
  process.exit(0);
}

// Every blob URL shares one store host: https://<store>.public.blob.vercel-storage.com/<pathname>
const blobHost = new URL(blobs[0].url).origin;

// ── 2. Copy objects to R2 (same keys) ─────────────────────────────────────
if (!WRITE) {
  console.log("\nDRY RUN — nothing copied or rewritten. Re-run with --write to apply.");
  for (const b of blobs.slice(0, 5)) {
    console.log(`  ${b.pathname} (${(b.size / 1024).toFixed(0)} KB) → /media/${b.pathname}`);
  }
  if (blobs.length > 5) console.log(`  … and ${blobs.length - 5} more.`);
  process.exit(0);
}

console.log("→ copying objects to R2 (same keys)…");
let copied = 0;
for (const b of blobs) {
  const res = await fetch(b.url);
  if (!res.ok) {
    console.error(`  ✗ download failed: ${b.pathname} (${res.status})`);
    continue;
  }
  const body = new Uint8Array(await res.arrayBuffer());
  const put = await r2.fetch(`${R2_BASE}/${b.pathname}`, {
    method: "PUT",
    body: body as unknown as BodyInit,
    headers: { "Content-Type": contentTypeFor(b.pathname) },
  });
  if (!put.ok) {
    console.error(`  ✗ R2 put failed: ${b.pathname} (${put.status})`);
    continue;
  }
  copied++;
  if (copied % 10 === 0) console.log(`  ${copied}/${blobs.length}`);
}
console.log(`  ✓ copied ${copied}/${blobs.length} objects.`);

// ── 3. Emit the DB URL rewrite as SQL ─────────────────────────────────────
// One REPLACE per column that can hold blob URLs. JSON gallery columns are
// plain text to REPLACE, so they're covered by the same statement.
const sql = `-- Generated by scripts/migrate-blob-to-r2.ts — rewrites Vercel Blob
-- URLs (${blobHost}/) to origin-relative /media/<key>.
BEGIN TRANSACTION;
UPDATE projects     SET image   = REPLACE(image, '${blobHost}/', '/media/'),
                        gallery = REPLACE(gallery, '${blobHost}/', '/media/');
UPDATE publications SET image   = REPLACE(image, '${blobHost}/', '/media/'),
                        gallery = REPLACE(gallery, '${blobHost}/', '/media/');
UPDATE news         SET image   = REPLACE(image, '${blobHost}/', '/media/');
UPDATE site_content SET about_portrait = REPLACE(about_portrait, '${blobHost}/', '/media/');
COMMIT;`;

mkdirSync(new URL("../drizzle/", import.meta.url), { recursive: true });
writeFileSync(new URL("../drizzle/rewrite.sql", import.meta.url), sql + "\n");

console.log("\nDone. Next steps:");
console.log(`  ✓ copied ${copied}/${blobs.length} objects to R2.`);
console.log(`  → apply the DB rewrite:`);
console.log(`      npx wrangler d1 execute ggeran-db --local  --file=drizzle/rewrite.sql`);
console.log(`      npx wrangler d1 execute ggeran-db --remote --file=drizzle/rewrite.sql`);
console.log(`  • Unsplash/seed URLs were intentionally left untouched.`);
console.log(`  • Keep the Vercel Blob store as a cold backup until the new site is verified.`);
