/**
 * Generate drizzle/seed.sql from src/db/seed-data.ts, for D1:
 *   npm run db:seed-sql                       # write drizzle/seed.sql
 *   npx wrangler d1 execute ggeran-db --local  --file=drizzle/seed.sql
 *   npx wrangler d1 execute ggeran-db --remote --file=drizzle/seed.sql
 * (or just `just db-seed local|remote`.)
 *
 * Idempotent: clears the content tables first; the site-content row is only
 * inserted when absent, so re-running never overwrites admin edits.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import {
  seedProjects,
  seedPublications,
  seedNews,
  seedSiteContent,
} from "../src/db/seed-data";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  if (Array.isArray(v)) return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

type Row = Record<string, unknown>;

const insert = (table: string, columns: string[], row: Row): string =>
  `INSERT INTO ${table} (${columns.join(", ")}) VALUES (${columns.map((c) => q(row[c])).join(", ")});`;

const lines: string[] = [
  "-- Generated by scripts/seed-sql.ts — do not edit by hand.",
  "BEGIN TRANSACTION;",
  "DELETE FROM news;",
  "DELETE FROM publications;",
  "DELETE FROM projects;",
];

for (const p of seedProjects) {
  lines.push(
    insert(
      "projects",
      ["slug", "title", "year", "date", "ref", "category", "location", "medium", "dimensions", "edition", "availability", "series", "featured", "weight", "image", "gallery", "body"],
      { ...p, gallery: p.gallery ?? [] },
    ),
  );
}
for (const p of seedPublications) {
  lines.push(
    insert(
      "publications",
      ["slug", "title", "year", "date", "ref", "category", "publisher", "author", "isbn", "pages", "format", "edition", "image", "gallery", "body"],
      { ...p, gallery: p.gallery ?? [] },
    ),
  );
}
for (const n of seedNews) {
  lines.push(insert("news", ["slug", "title", "date", "summary", "image", "body"], { ...n }));
}

// Singleton site content: only seed when absent (snake_case columns).
const sc = seedSiteContent as unknown as Row;
const scCols: [string, string][] = [
  ["contactEmail", "contact_email"],
  ["contactInstagramUrl", "contact_instagram_url"],
  ["contactInstagramHandle", "contact_instagram_handle"],
  ["contactIntro", "contact_intro"],
  ["aboutPortrait", "about_portrait"],
  ["aboutBio", "about_bio"],
  ["aboutExhibitions", "about_exhibitions"],
  ["availableHeading", "available_heading"],
  ["availableIntro", "available_intro"],
  ["heroTitle", "hero_title"],
  ["heroSubtitle", "hero_subtitle"],
  ["navProjectsLabel", "nav_projects_label"],
  ["navAvailableLabel", "nav_available_label"],
  ["navAboutLabel", "nav_about_label"],
  ["navContactLabel", "nav_contact_label"],
  ["navShowPublications", "nav_show_publications"],
  ["navShowNews", "nav_show_news"],
  ["projectCategories", "project_categories"],
  ["navExtraLinks", "nav_extra_links"],
];
lines.push(
  `INSERT INTO site_content (id, ${scCols.map(([, c]) => c).join(", ")}) ` +
    `VALUES (1, ${scCols.map(([k]) => q(sc[k])).join(", ")}) ` +
    `ON CONFLICT(id) DO NOTHING;`,
);
lines.push("COMMIT;");

mkdirSync(new URL("../drizzle/", import.meta.url), { recursive: true });
writeFileSync(new URL("../drizzle/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`✓ wrote drizzle/seed.sql (${seedProjects.length} projects, ${seedPublications.length} publications, ${seedNews.length} news).`);
